version: '3.8'

services:
  movie-frontend:
    build: ./movie-frontend
    ports:
      - "4200:4200"
    depends_on:
      - movie-backend

  movie-backend:
    build: ./movie-backend
    ports:
      - "8080:8080"
    env_file:
      - .env